version: 0.2

env:
  variables:
    AWS_REGION: "ap-south-1"
    REPOSITORY_NAME: "sample-java-app"
    ECR_URI: "699475953949.dkr.ecr.ap-south-1.amazonaws.com/sample-java-app"
    IMAGE_TAG: "latest"

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "ðŸ“¦ Setting up Maven settings.xml"
      - mkdir -p ~/.m2
      - cp settings.xml ~/.m2/settings.xml

      - echo "ðŸ“¦ Fetching CodeArtifact Domain Name..."
      - export DOMAIN_NAME=$(aws codeartifact list-domains --region $AWS_REGION --query 'domains[0].name' --output text)
      - echo "âœ… DOMAIN_NAME = $DOMAIN_NAME"

      - echo "ðŸ‘¤ Fetching AWS Account ID..."
      - export DOMAIN_OWNER=$(aws sts get-caller-identity --query 'Account' --output text)
      - echo "âœ… DOMAIN_OWNER = $DOMAIN_OWNER"

      - echo "ðŸ” Getting CodeArtifact auth token..."
      - export CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token \
          --domain "$DOMAIN_NAME" \
          --domain-owner "$DOMAIN_OWNER" \
          --region "$AWS_REGION" \
          --query authorizationToken \
          --output text)

      - echo "ðŸ”— Getting Maven repository endpoint..."
      - export MAVEN_REPO_URL=$(aws codeartifact get-repository-endpoint \
          --domain "$DOMAIN_NAME" \
          --domain-owner "$DOMAIN_OWNER" \
          --repository "$REPOSITORY_NAME" \
          --format maven \
          --region "$AWS_REGION" \
          --query repositoryEndpoint \
          --output text)
      - echo "âœ… Maven Repo URL = $MAVEN_REPO_URL"

  pre_build:
    commands:
      - echo "ðŸ—ï¸ Building JAR using CodeArtifact dependencies..."
      - mvn clean package -DskipTests -s ~/.m2/settings.xml
      - echo "ðŸ” Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_REGION \
        | docker login --username AWS --password-stdin $ECR_URI

  build:
    commands:
      - echo "ðŸ“¤ Deploying JAR to CodeArtifact..."
      - mvn deploy -DskipTests -s ~/.m2/settings.xml
      - echo "ðŸ³ Building Docker image..."
      - docker build -t $ECR_URI:$IMAGE_TAG .

  post_build:
    commands:
      - echo "ðŸ“¤ Pushing Docker image..."
      - docker push $ECR_URI:$IMAGE_TAG
      - echo "ðŸ“ Creating imagedefinitions.json..."
      - echo "[{\"name\":\"sample-java-app\",\"imageUri\":\"$ECR_URI:$IMAGE_TAG\"}]" > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json

