version: 0.2

env:
  variables:
    AWS_REGION: "ap-south-1"
    DOMAIN_NAME: "sample"
    DOMAIN_OWNER: "699475953949"
    REPOSITORY_NAME: "sample-java-app"
    ECR_URI: "699475953949.dkr.ecr.ap-south-1.amazonaws.com/sample-java-app"
    IMAGE_TAG: "latest"

phases:
  install:
    runtime-versions:
      java: corretto17
      docker: 20
    commands:
      - echo "ðŸ“¦ Copying settings.xml to Maven home"
      - mkdir -p ~/.m2
      - cp settings.xml ~/.m2/settings.xml
      - echo "ðŸ” Getting CodeArtifact token..."
      - export CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token \
          --domain $DOMAIN_NAME \
          --domain-owner $DOMAIN_OWNER \
          --region $AWS_REGION \
          --query authorizationToken \
          --output text)

  pre_build:
    commands:
      - echo "ðŸ—ï¸ Building JAR..."
      - mvn clean package -DskipTests
      - echo "ðŸ” Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_REGION \
        | docker login --username AWS --password-stdin $ECR_URI

  build:
    commands:
      - echo "ðŸ“¤ Deploying JAR to CodeArtifact..."
      - mvn deploy
      - echo "ðŸ³ Building Docker image..."
      - docker build -t $ECR_URI:$IMAGE_TAG .

  post_build:
    commands:
      - echo "ðŸ“¤ Pushing Docker image..."
      - docker push $ECR_URI:$IMAGE_TAG
      - echo "ðŸ“ Creating imagedefinitions.json..."
      - echo "[{\"name\":\"sample-java-app\",\"imageUri\":\"$ECR_URI:$IMAGE_TAG\"}]" > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json

